#Pull base image
#-----------------
FROM mongo

#Author
#-------
MAINTAINER Jennifer Reif <jennifer@thehecklers.org,@JMHReif>

#expose the default port
EXPOSE 27017

#Set default container commands
#-------------------------------
CMD ["mongod","--smallfiles"]
